{
  pkgs,
  inputs,
  ...
}: {
  nixpkgs.config.allowUnfree = true;
  environment = {
    systemPackages = with pkgs; [
      # system packages
      openrgb
      hyprland
      waybar
      mako
      wl-clipboard
      vulkan-tools
      libGL
      libGLU
      cudatoolkit
      zsh
      oh-my-zsh
      home-manager
      nh
      pipewire
      pavucontrol
      pulseaudio
      bluez
      slurp
      grim
      xdg-desktop-portal
      xdg-desktop-portal-hyprland
      xdg-desktop-portal-gtk
      kdePackages.xwaylandvideobridge
      wpaperd
      hyprcursor
      bibata-cursors
      rose-pine-hyprcursor

      # programming related
      gcc
      ninja
      gdb
      clang
      go
      ghc
      python3
      typst
      typstyle
      tinymist
      nil
      alejandra
      pkg-config
      qbe
      gnumake
      gradle
      stylua
      lua-language-server
      clang-tools
      nodejs
      typescript
      typescript-language-server
      pnpm
      jdk
      cloudflared
      wgcf
      jq
      alejandra

      # cli utils
      vim
      wget
      curl
      git
      file
      tree
      unzip
      nettools
      pciutils
      usbutils
      ripgrep
      fd
      fastfetch
      glxinfo
      zoxide
      brightnessctl
      eza
      john
      hashcat
      qbittorrent-nox
      tmux
      exiftool
      xdg-utils
      pfetch
      ffmpeg
      cargo-msrv
      tokei
      steam-run
      sl
      neovim
      github-cli
      bc
      dioxus-cli
      wasm-pack
      cht-sh
      cmus

      # gui apps
      kitty
      prismlauncher
      steam
      wofi
      kdePackages.kdenlive
      evince
      vlc
      geogebra6
      firefox
      obs-studio
      feh
      signal-desktop
      wine
      winetricks
      nwg-displays
      protonvpn-gui
      qbittorrent
      unar
      anki
      keymapp
      gimp
      telegram-desktop
      waydroid
      kdePackages.ark
      vesktop
    ];
    plasma6.excludePackages = with pkgs.kdePackages; [
      plasma-browser-integration
      konsole
      oxygen
    ];
  };
}
